# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'vphone' do

  pod 'Firebase/Core', '~> 5.3.0'
  pod 'Firebase/Messaging'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for vphone

  pod 'react-native-network-info', :path => '../node_modules/react-native-network-info'

  pod 'CodePush', :path => '../node_modules/react-native-code-push'

  target 'vphoneTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'vphone-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for vphone-tvOS

  target 'vphone-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
